language: java
jdk:
- openjdk7
- oraclejdk7
os:
  - linux
  - osx
notifications:
    on_success: [change] # default: change [always|never|change] 
    on_failure: [change] # default: always [always|never|change]
